export type MarketplaceCategory =
  | "Hair"
  | "Nails"
  | "Spa"
  | "Cleaning"
  | "Home Repairs"
  | "Photography";

export type MarketplaceListing = {
  id: string;
  name: string;
  category: MarketplaceCategory;
  price: number;
  rating: number;
  reviews: number;
  location: string;
  description: string;
  image: string; // path under public/images/marketplace/
  availableSlots: string[];
};

export const categories: MarketplaceCategory[] = [
  "Hair",
  "Nails",
  "Spa",
  "Cleaning",
  "Home Repairs",
  "Photography",
];

export const marketplaceListings: MarketplaceListing[] = [
  // ── Hair ──────────────────────────────────────────
  {
    id: "luxe-hair-studio",
    name: "Luxe Hair Studio",
    category: "Hair",
    price: 15000,
    rating: 4.8,
    reviews: 234,
    location: "Lekki, Lagos",
    description: "Premium braids, cuts, and styling by top-tier hair artists.",
    image: "/images/marketplace/hair-luxe-studio.jpg",
    availableSlots: [
      "Mon 10:00",
      "Mon 14:00",
      "Tue 09:00",
      "Tue 11:00",
      "Wed 10:00",
      "Thu 13:00",
      "Fri 09:00",
      "Sat 10:00",
    ],
  },
  {
    id: "braid-palace",
    name: "Braid Palace",
    category: "Hair",
    price: 8000,
    rating: 4.5,
    reviews: 189,
    location: "Surulere, Lagos",
    description: "Affordable box braids, cornrows, and twist outs.",
    image: "/images/marketplace/hair-braid-palace.jpg",
    availableSlots: [
      "Mon 09:00",
      "Mon 11:00",
      "Wed 09:00",
      "Wed 14:00",
      "Fri 10:00",
      "Sat 09:00",
    ],
  },
  {
    id: "curls-and-co",
    name: "Curls & Co",
    category: "Hair",
    price: 12000,
    rating: 4.7,
    reviews: 312,
    location: "Victoria Island, Lagos",
    description: "Natural hair care, silk presses, and protective styles.",
    image: "/images/marketplace/hair-curls-co.jpg",
    availableSlots: [
      "Tue 10:00",
      "Tue 14:00",
      "Thu 09:00",
      "Thu 11:00",
      "Fri 13:00",
      "Sat 11:00",
    ],
  },
  {
    id: "fade-house",
    name: "Fade House Barbers",
    category: "Hair",
    price: 3500,
    rating: 4.9,
    reviews: 421,
    location: "Yaba, Lagos",
    description: "Clean fades, tapers, and classic cuts for men.",
    image: "/images/marketplace/hair-fade-house.jpg",
    availableSlots: [
      "Mon 08:00",
      "Mon 10:00",
      "Mon 14:00",
      "Tue 08:00",
      "Wed 09:00",
      "Thu 10:00",
      "Fri 08:00",
      "Sat 08:00",
    ],
  },

  // ── Nails ─────────────────────────────────────────
  {
    id: "polish-lounge",
    name: "Polish Lounge",
    category: "Nails",
    price: 5000,
    rating: 4.6,
    reviews: 156,
    location: "Ikoyi, Lagos",
    description: "Gel nails, acrylics, nail art, and manicure-pedicure combos.",
    image: "/images/marketplace/nails-polish-lounge.jpg",
    availableSlots: [
      "Mon 11:00",
      "Tue 10:00",
      "Wed 14:00",
      "Thu 11:00",
      "Fri 10:00",
      "Sat 09:00",
    ],
  },
  {
    id: "nail-art-studio",
    name: "Nail Art Studio",
    category: "Nails",
    price: 7500,
    rating: 4.8,
    reviews: 203,
    location: "Lekki, Lagos",
    description: "Custom nail designs, chrome finishes, and luxury pedicures.",
    image: "/images/marketplace/nails-art-studio.jpg",
    availableSlots: [
      "Mon 09:00",
      "Tue 11:00",
      "Wed 10:00",
      "Thu 09:00",
      "Fri 14:00",
      "Sat 10:00",
    ],
  },
  {
    id: "tip-top-nails",
    name: "Tip Top Nails",
    category: "Nails",
    price: 3500,
    rating: 4.4,
    reviews: 98,
    location: "Ikeja, Lagos",
    description: "Quick manis, pedis, and classic French tips at friendly prices.",
    image: "/images/marketplace/nails-tip-top.jpg",
    availableSlots: [
      "Mon 10:00",
      "Wed 11:00",
      "Fri 09:00",
      "Sat 10:00",
      "Sat 14:00",
    ],
  },

  // ── Spa ───────────────────────────────────────────
  {
    id: "serenity-spa",
    name: "Serenity Spa & Wellness",
    category: "Spa",
    price: 25000,
    rating: 4.9,
    reviews: 347,
    location: "Victoria Island, Lagos",
    description: "Full-body massage, aromatherapy, and detox wraps.",
    image: "/images/marketplace/spa-serenity.jpg",
    availableSlots: [
      "Mon 10:00",
      "Mon 14:00",
      "Tue 11:00",
      "Wed 10:00",
      "Thu 13:00",
      "Fri 10:00",
      "Sat 09:00",
    ],
  },
  {
    id: "zen-garden",
    name: "Zen Garden Spa",
    category: "Spa",
    price: 18000,
    rating: 4.7,
    reviews: 215,
    location: "Lekki, Lagos",
    description: "Hot stone therapy, foot reflexology, and couples packages.",
    image: "/images/marketplace/spa-zen-garden.jpg",
    availableSlots: [
      "Tue 09:00",
      "Tue 14:00",
      "Thu 10:00",
      "Fri 11:00",
      "Sat 10:00",
      "Sat 14:00",
    ],
  },
  {
    id: "oasis-wellness",
    name: "Oasis Wellness Center",
    category: "Spa",
    price: 15000,
    rating: 4.6,
    reviews: 178,
    location: "Ikoyi, Lagos",
    description: "Swedish massage, body scrubs, and steam room access.",
    image: "/images/marketplace/spa-oasis.jpg",
    availableSlots: [
      "Mon 09:00",
      "Wed 10:00",
      "Wed 14:00",
      "Fri 09:00",
      "Sat 11:00",
    ],
  },

  // ── Cleaning ──────────────────────────────────────
  {
    id: "sparkle-clean",
    name: "Sparkle Clean Services",
    category: "Cleaning",
    price: 8000,
    rating: 4.5,
    reviews: 142,
    location: "Lagos Island, Lagos",
    description: "Deep home cleaning, post-renovation cleanup, and move-in service.",
    image: "/images/marketplace/cleaning-sparkle.jpg",
    availableSlots: [
      "Mon 08:00",
      "Tue 08:00",
      "Wed 08:00",
      "Thu 08:00",
      "Fri 08:00",
      "Sat 09:00",
    ],
  },
  {
    id: "fresh-start",
    name: "Fresh Start Cleaning",
    category: "Cleaning",
    price: 12000,
    rating: 4.7,
    reviews: 203,
    location: "Lekki, Lagos",
    description: "Office and residential cleaning with eco-friendly products.",
    image: "/images/marketplace/cleaning-fresh-start.jpg",
    availableSlots: [
      "Mon 09:00",
      "Tue 09:00",
      "Wed 09:00",
      "Thu 09:00",
      "Fri 09:00",
    ],
  },
  {
    id: "tidy-home",
    name: "Tidy Home Pros",
    category: "Cleaning",
    price: 6000,
    rating: 4.3,
    reviews: 87,
    location: "Surulere, Lagos",
    description: "Regular home cleaning, laundry folding, and kitchen detailing.",
    image: "/images/marketplace/cleaning-tidy-home.jpg",
    availableSlots: [
      "Mon 10:00",
      "Wed 10:00",
      "Fri 10:00",
      "Sat 08:00",
    ],
  },

  // ── Home Repairs ──────────────────────────────────
  {
    id: "fix-it-ng",
    name: "Fix-It Nigeria",
    category: "Home Repairs",
    price: 10000,
    rating: 4.6,
    reviews: 189,
    location: "Ikeja, Lagos",
    description: "Plumbing, electrical, and general handyman repairs.",
    image: "/images/marketplace/repairs-fix-it.jpg",
    availableSlots: [
      "Mon 08:00",
      "Tue 08:00",
      "Wed 08:00",
      "Thu 08:00",
      "Fri 08:00",
    ],
  },
  {
    id: "home-heroes",
    name: "Home Heroes",
    category: "Home Repairs",
    price: 15000,
    rating: 4.8,
    reviews: 267,
    location: "Victoria Island, Lagos",
    description: "AC servicing, generator maintenance, and installations.",
    image: "/images/marketplace/repairs-home-heroes.jpg",
    availableSlots: [
      "Mon 09:00",
      "Tue 09:00",
      "Wed 09:00",
      "Thu 09:00",
      "Fri 09:00",
      "Sat 09:00",
    ],
  },
  {
    id: "quick-fix",
    name: "Quick Fix Solutions",
    category: "Home Repairs",
    price: 7000,
    rating: 4.4,
    reviews: 121,
    location: "Yaba, Lagos",
    description: "Tile fixing, painting, and minor carpentry work.",
    image: "/images/marketplace/repairs-quick-fix.jpg",
    availableSlots: [
      "Mon 10:00",
      "Wed 10:00",
      "Fri 10:00",
      "Sat 10:00",
    ],
  },

  // ── Photography ───────────────────────────────────
  {
    id: "snap-studio",
    name: "Snap Studio Lagos",
    category: "Photography",
    price: 30000,
    rating: 4.9,
    reviews: 398,
    location: "Lekki, Lagos",
    description: "Portrait shoots, event coverage, and product photography.",
    image: "/images/marketplace/photo-snap-studio.jpg",
    availableSlots: [
      "Mon 10:00",
      "Tue 10:00",
      "Wed 10:00",
      "Thu 10:00",
      "Fri 10:00",
      "Sat 09:00",
    ],
  },
  {
    id: "lens-masters",
    name: "Lens Masters",
    category: "Photography",
    price: 20000,
    rating: 4.7,
    reviews: 176,
    location: "Ikoyi, Lagos",
    description: "Pre-wedding shoots, birthday photos, and family portraits.",
    image: "/images/marketplace/photo-lens-masters.jpg",
    availableSlots: [
      "Mon 09:00",
      "Tue 09:00",
      "Thu 09:00",
      "Sat 09:00",
      "Sat 14:00",
    ],
  },
  {
    id: "pixel-perfect",
    name: "Pixel Perfect Photography",
    category: "Photography",
    price: 15000,
    rating: 4.5,
    reviews: 134,
    location: "Surulere, Lagos",
    description: "Corporate headshots, CV photos, and social media content.",
    image: "/images/marketplace/photo-pixel-perfect.jpg",
    availableSlots: [
      "Mon 11:00",
      "Wed 11:00",
      "Fri 11:00",
      "Sat 10:00",
    ],
  },
];
