"use client";

import confetti from "canvas-confetti";
import { AnimatePresence, motion } from "framer-motion";
import { Check, Copy, Delete, Download, ReceiptText, X } from "lucide-react";
import { Drawer } from "vaul";
import { useState } from "react";

import { Button } from "@/components/ui/button";

type PinModalProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
  title?: string;
  amount?: string;
};

export function PinModal({
  open,
  onOpenChange,
  onSuccess,
  title = "Confirm payment",
  amount,
}: PinModalProps) {
  const [pin, setPin] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [hasError, setHasError] = useState(false);
  const [successVisible, setSuccessVisible] = useState(false);
  const [receipt, setReceipt] = useState<{
    reference: string;
    timestamp: string;
  } | null>(null);

  const handleOpenChange = (nextOpen: boolean) => {
    if (!nextOpen) {
      setPin("");
      setIsProcessing(false);
      setHasError(false);
      setSuccessVisible(false);
      setReceipt(null);
    }
    onOpenChange(nextOpen);
  };

  const submitPin = () => {
    if (pin !== "1234") {
      setHasError(true);
      return;
    }

    setHasError(false);
    setIsProcessing(true);
    window.setTimeout(() => {
      setIsProcessing(false);
      setSuccessVisible(true);
      setReceipt({
        reference: `NEX-${Date.now().toString(36).toUpperCase().slice(-8)}`,
        timestamp: new Intl.DateTimeFormat("en-NG", {
          dateStyle: "medium",
          timeStyle: "short",
        }).format(new Date()),
      });
      confetti({ particleCount: 90, spread: 70, origin: { y: 0.7 } });
    }, 800);
  };

  const finish = () => {
    setSuccessVisible(false);
    handleOpenChange(false);
    onSuccess();
  };

  const addDigit = (digit: string) => {
    setHasError(false);
    setPin((value) => (value.length < 4 ? `${value}${digit}` : value));
  };

  const downloadReceipt = () => {
    if (!receipt) return;
    const receiptHtml = `<!doctype html>
<html><head><meta charset="utf-8"><title>Ravecard receipt ${receipt.reference}</title>
<style>body{margin:0;background:#eef1f5;color:#101828;font:15px Arial,sans-serif}.receipt{width:360px;margin:40px auto;background:#fff;padding:28px;box-shadow:0 12px 35px #10182822}.brand{text-align:center;font-size:24px;font-weight:700;color:#155eef}.status{text-align:center;margin:24px 0;color:#12b76a;font-weight:700}.line{border-top:1px dashed #98a2b3;margin:20px 0}.row{display:flex;justify-content:space-between;gap:16px;margin:13px 0;color:#667085}.row strong{color:#101828;text-align:right}.total{font-size:22px;font-weight:700;color:#101828}.footer{text-align:center;margin-top:24px;color:#667085;font-size:12px}@media print{body{background:#fff}.receipt{margin:0;box-shadow:none}}</style></head>
<body><main class="receipt"><div class="brand">Ravecard</div><div class="status">PAYMENT SUCCESSFUL</div><div class="line"></div><div class="row"><span>Service</span><strong>${title}</strong></div><div class="row"><span>Amount</span><strong class="total">${amount ?? "-"}</strong></div><div class="row"><span>Date and time</span><strong>${receipt.timestamp}</strong></div><div class="row"><span>Reference</span><strong>${receipt.reference}</strong></div><div class="row"><span>Status</span><strong>Successful</strong></div><div class="line"></div><div class="footer">This receipt was generated by the Ravecard demo.</div></main><script>window.print()</script></body></html>`;
    const url = URL.createObjectURL(
      new Blob([receiptHtml], { type: "text/html" }),
    );
    window.open(url, "_blank", "noopener,noreferrer");
    window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
  };

  return (
    <Drawer.Root
      open={open}
      onOpenChange={handleOpenChange}
      dismissible={!isProcessing}
    >
      <Drawer.Portal>
        <Drawer.Overlay className="fixed inset-0 z-40 bg-slate-950/65 backdrop-blur-md" />
        <Drawer.Content className="!h-auto fixed inset-x-0 bottom-0 z-50 mx-auto max-h-[calc(100dvh-1rem)] w-full max-w-md overflow-hidden rounded-t-[30px] border border-border bg-card p-5 shadow-2xl outline-none md:bottom-auto md:top-1/2 md:-translate-y-1/2 md:rounded-[30px] md:p-7">
          <div className="mx-auto mb-5 h-1.5 w-12 rounded-full bg-muted md:hidden" />
          <Button
            variant="ghost"
            size="icon-sm"
            type="button"
            onClick={() => handleOpenChange(false)}
            className="absolute right-4 top-4 text-muted-foreground hover:bg-muted hover:text-foreground"
            aria-label="Close PIN confirmation"
          >
            <X />
          </Button>
          <AnimatePresence mode="wait">
            {successVisible ? (
              <motion.div
                key="success"
                initial={{ opacity: 0, scale: 0.92 }}
                animate={{ opacity: 1, scale: 1 }}
                className="py-8 text-center"
              >
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: "spring", stiffness: 300, damping: 16 }}
                  className="mx-auto grid size-20 place-items-center rounded-full bg-emerald-500 text-white shadow-[0_0_35px_rgba(52,211,153,0.55)]"
                >
                  <Check className="size-10" />
                </motion.div>
                <h2 className="mt-6 font-heading text-2xl font-semibold">
                  Payment successful
                </h2>
                  <p className="mt-2 text-sm text-muted-foreground">
                    {title} has been prepared in this demo.
                  </p>
                {amount && (
                  <p className="mt-4 font-heading text-3xl font-semibold text-emerald-300">
                    {amount}
                  </p>
                )}
                {receipt && (
                  <div className="mt-5 rounded-2xl border border-border bg-card p-4 text-left text-foreground shadow-lg">
                    <div className="flex items-center justify-between border-b border-dashed border-border pb-3">
                      <span className="flex items-center gap-2 font-heading font-semibold">
                        <ReceiptText className="size-4 text-primary" /> Ravecard
                        receipt
                      </span>
                      <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-success">
                        Paid
                      </span>
                    </div>
                    <div className="py-3 text-center">
                      <p className="text-xs uppercase tracking-[0.16em] text-muted-foreground">
                        Total paid
                      </p>
                      <p className="mt-1 font-heading text-2xl font-semibold">
                        {amount ?? "-"}
                      </p>
                    </div>
                    <div className="flex items-center justify-between gap-3 text-xs text-muted-foreground">
                      <span>Date and time</span>
                      <span className="text-right text-foreground">
                        {receipt.timestamp}
                      </span>
                    </div>
                    <div className="mt-2 flex items-center justify-between gap-3 text-xs">
                      <span className="text-muted-foreground">Reference</span>
                      <span className="flex items-center gap-2 font-mono text-foreground">
                        {receipt.reference}
                        <Copy className="size-3.5" />
                      </span>
                    </div>
                  </div>
                )}
                <Button
                  type="button"
                  variant="ghost"
                  onClick={downloadReceipt}
                  className="mt-4 h-9 w-full gap-2 text-muted-foreground hover:bg-muted hover:text-foreground"
                >
                  <Download className="size-4" /> Open printable receipt
                </Button>
                <Button
                  type="button"
                  onClick={finish}
                  className="mt-7 h-11 w-full bg-emerald-500 text-white hover:bg-emerald-400"
                >
                  Done
                </Button>
              </motion.div>
            ) : (
              <motion.div
                key="pin"
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
              >
                <p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">
                  Ravecard secure step
                </p>
                <Drawer.Title className="mt-2 font-heading text-2xl font-semibold">
                  {title}
                </Drawer.Title>
                <Drawer.Description className="mt-2 text-sm text-muted-foreground">
                  Enter your four-digit demo PIN to continue.
                </Drawer.Description>
                {amount && (
                  <p className="mt-5 font-heading text-3xl font-semibold">
                    {amount}
                  </p>
                )}
                <motion.div
                  animate={hasError ? { x: [0, -8, 8, -5, 5, 0] } : { x: 0 }}
                  className="mt-6 flex justify-center gap-3"
                >
                  {Array.from({ length: 4 }, (_, index) => (
                    <span
                      key={index}
                      className={`size-3 rounded-full border ${index < pin.length ? "border-primary bg-primary shadow-[0_0_14px_var(--primary)]" : "border-border"}`}
                    />
                  ))}
                </motion.div>
                {hasError && (
                  <p className="mt-3 text-center text-sm text-red-300">
                    Incorrect PIN. Use 1234 for this demo.
                  </p>
                )}
                <div className="mx-auto mt-5 grid max-w-xs grid-cols-3 gap-2">
                  {["1", "2", "3", "4", "5", "6", "7", "8", "9"].map(
                    (digit) => (
                      <button
                        key={digit}
                        type="button"
                        onClick={() => addDigit(digit)}
                        className="grid h-11 place-items-center rounded-xl border border-border bg-muted text-lg font-semibold transition hover:bg-muted/80 active:scale-95"
                      >
                        {digit}
                      </button>
                    ),
                  )}
                  <span />
                  <button
                    type="button"
                    onClick={() => addDigit("0")}
                    className="grid h-11 place-items-center rounded-xl border border-white/10 bg-white/8 text-lg font-semibold transition hover:bg-white/15 active:scale-95"
                  >
                    0
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setHasError(false);
                      setPin((value) => value.slice(0, -1));
                    }}
                    className="grid h-11 place-items-center rounded-xl border border-border bg-muted transition hover:bg-muted/80 active:scale-95"
                    aria-label="Delete last PIN digit"
                  >
                    <Delete className="size-5" />
                  </button>
                </div>
                <Button
                  type="button"
                  onClick={submitPin}
                  disabled={pin.length !== 4 || isProcessing}
                  className="mt-4 h-11 w-full bg-primary text-primary-foreground hover:bg-primary/85"
                >
                  {isProcessing ? "Processing..." : "Confirm payment"}
                </Button>
                <p className="mt-3 text-center text-xs text-muted-foreground">
                  Demo PIN: 1234
                </p>
              </motion.div>
            )}
          </AnimatePresence>
        </Drawer.Content>
      </Drawer.Portal>
    </Drawer.Root>
  );
}
