"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useSyncExternalStore,
  type ReactNode,
} from "react";

export type Language = "en" | "fr" | "yo" | "ha" | "ig" | "es" | "ar" | "pt";

export const languageOptions = [
  { label: "English", value: "en" },
  { label: "French", value: "fr" },
  { label: "Yoruba", value: "yo" },
  { label: "Hausa", value: "ha" },
  { label: "Igbo", value: "ig" },
  { label: "Spanish", value: "es" },
  { label: "Arabic", value: "ar" },
  { label: "Portuguese", value: "pt" },
] as const;

export const translations: Record<Language, Record<string, string>> = {
  en: {
    settings: "Settings",
    profile: "Profile",
    home: "Home",
    wallet: "Wallet",
    bills: "Bills",
    airtime: "Airtime & Data",
    signIn: "Sign In",
    savePreferences: "Save preferences",
    walletTitle: "Keep your money close.",
    billsTitle: "Keep the essentials running.",
    airtimeTitle: "Stay connected.",
    bettingTitle: "Fund your play wallet.",
    giftTitle: "Buy or sell a gift card.",
    profileTitle: "Your Ravecard identity.",
    settingsTitle: "Make Ravecard yours.",
    availableBalance: "Available balance",
    quickAccess: "Quick access",
    recentTransactions: "Recent transactions",
    personalWallet: "Personal wallet",
    goodToSeeYou: "Good to see you",
    homeTitle: "Your money, in motion.",
    homeDescription: "Move money. Move freely. Everything you need, one tap away.",
    viewWallet: "View wallet",
    pulseNote: "Ravecard Pulse",
    smallMoves: "Your card. Your rules. Your freedom.",
    checkActivity: "See recent activity",
    moreServices: "More ways to move freely — coming soon as Ravecard grows.",
    exploreMore: "Explore more",
    twoFactor: "Two-factor authentication",
    authenticator: "Authenticator app",
    smsCode: "SMS code",
    emailCode: "Email code",
    backupCodes: "Backup codes",
    recommended: "Recommended",
    verify: "Verify",
    sendCode: "Send code",
    checking: "Checking...",
    setupAuthenticator: "Set up your authenticator",
    twoFactorEnabled: "2FA enabled",
    disableTwoFactor: "Disable two-factor authentication?",
  },
  fr: {
    settings: "Parametres",
    profile: "Profil",
    home: "Accueil",
    wallet: "Portefeuille",
    bills: "Factures",
    airtime: "Recharge & donnees",
    signIn: "Se connecter",
    savePreferences: "Enregistrer",
    walletTitle: "Gardez votre argent pres de vous.",
    billsTitle: "Gardez l'essentiel en marche.",
    airtimeTitle: "Restez connecte.",
    bettingTitle: "Alimentez votre portefeuille de jeu.",
    giftTitle: "Achetez ou vendez une carte cadeau.",
    profileTitle: "Votre identite Ravecard.",
    settingsTitle: "Faites de Ravecard votre espace.",
    availableBalance: "Solde disponible",
    quickAccess: "Acces rapide",
    recentTransactions: "Transactions recentes",
    personalWallet: "Portefeuille personnel",
    goodToSeeYou: "Heureux de vous revoir",
    homeTitle: "Votre argent en mouvement.",
    homeDescription: "Deplacez votre argent librement. Tout ce dont vous avez besoin, en un toucher.",
    viewWallet: "Voir le portefeuille",
    pulseNote: "Ravecard Pulse",
    smallMoves: "Votre carte. Vos regles. Votre liberte.",
    checkActivity: "Voir l'activite recente",
    moreServices: "D'autres moyens de bouger librement — bientot sur Ravecard.",
    exploreMore: "Explorer davantage",
    twoFactor: "Authentification a deux facteurs",
    authenticator: "Application d'authentification",
    smsCode: "Code SMS",
    emailCode: "Code e-mail",
    backupCodes: "Codes de secours",
    recommended: "Recommande",
    verify: "Verifier",
    sendCode: "Envoyer le code",
    checking: "Verification...",
    setupAuthenticator: "Configurer votre authentificateur",
    twoFactorEnabled: "2FA activee",
    disableTwoFactor: "Desactiver l'authentification a deux facteurs ?",
  },
  yo: {
    settings: "Awon eto",
    profile: "Profaili",
    home: "Ile",
    wallet: "Apamowo",
    bills: "Owo isanwo",
    airtime: "Airtime ati data",
    signIn: "Wole",
    savePreferences: "Fi awon eto pam",
    walletTitle: "Pa owo re mo ara re.",
    billsTitle: "Jeki awon pataki ma n ṣiṣẹ.",
    airtimeTitle: "Wa ni asopọ.",
    bettingTitle: "Fi owo kun apamowo ere re.",
    giftTitle: "Ra tabi ta kaadi ebun.",
    profileTitle: "Idanimọ Ravecard rẹ.",
    settingsTitle: "Jeki Ravecard je tire.",
    availableBalance: "Iwontunwonsi to wa",
    quickAccess: "Wiwọle kiakia",
    recentTransactions: "Awon iṣowo to ṣẹṣẹ",
    personalWallet: "Apamowo ti ara ẹni",
    goodToSeeYou: "Inu mi dun lati ri e",
    homeTitle: "Owo re wa ni gbigbe.",
    homeDescription: "Fi owo re lọ gbogbo. Igbagbogbo ohun ti o nilo, nikan tap.",
    viewWallet: "Wo apamowo",
    pulseNote: "Ravecard Pulse",
    smallMoves: "Kaadi re. Ilana re. Ododo re.",
    checkActivity: "Wo iṣẹ to ṣẹṣẹ",
    moreServices: "Awon ọna ti a lọ sinu ododo si — wa ni Ravecard.",
    exploreMore: "Ṣawari diẹ sii",
    twoFactor: "Ijẹrisi ọna meji",
    authenticator: "App ijẹrisi",
    smsCode: "Koodu SMS",
    emailCode: "Koodu imeeli",
    backupCodes: "Awon koodu afẹyinti",
    recommended: "A ṣe iṣeduro",
    verify: "Jẹrisi",
    sendCode: "Firanṣẹ koodu",
    checking: "N ṣayẹwo...",
    setupAuthenticator: "Ṣeto app ijẹrisi rẹ",
    twoFactorEnabled: "2FA ti ṣiṣẹ",
    disableTwoFactor: "Pa ijẹrisi ọna meji?",
  },
  ha: {
    settings: "Saituna",
    profile: "Bayani",
    home: "Gida",
    wallet: "Jaka",
    bills: "Kudade",
    airtime: "Airtime da data",
    signIn: "Shiga",
    savePreferences: "Ajiye saituna",
    walletTitle: "Rike kudinka kusa.",
    billsTitle: "Kula da muhimman abubuwa.",
    airtimeTitle: "Kasance a hade.",
    bettingTitle: "Cika jakar wasanka.",
    giftTitle: "Saya ko sayar da katin kyauta.",
    profileTitle: "Bayanan Ravecard dinka.",
    settingsTitle: "Mayar da Ravecard naka.",
    availableBalance: "Ragowar kudi",
    quickAccess: "Samun sauri",
    recentTransactions: "Ma'amaloli na baya-bayan nan",
    personalWallet: "Jakar mutum",
    goodToSeeYou: "Na yi farin cikin ganinka",
    homeTitle: "Kudinka yana tafiya.",
    homeDescription: "Sanya kudinka cikin wani. Komai da kuke bukata, ta hanyar ta.",
    viewWallet: "Duba jaka",
    pulseNote: "Ravecard Pulse",
    smallMoves: "Jakar ka. Doka ka. Kyauta ka.",
    checkActivity: "Duba ayyukan baya",
    moreServices: "Ƙarin hanyoyin motsa kyauta — za su bayyana a Ravecard.",
    exploreMore: "Bincika fiye",
    twoFactor: "Tabbatarwa mataki biyu",
    authenticator: "Manhajar tabbatarwa",
    smsCode: "Lambar SMS",
    emailCode: "Lambar imel",
    backupCodes: "Lambobin ajiya",
    recommended: "An ba da shawara",
    verify: "Tabbatar",
    sendCode: "Aika lamba",
    checking: "Ana dubawa...",
    setupAuthenticator: "Saita manhajar tabbatarwa",
    twoFactorEnabled: "2FA yana aiki",
    disableTwoFactor: "A kashe tabbatarwa mataki biyu?",
  },
  ig: {
    settings: "Ntọala",
    profile: "Profaịlụ",
    home: "Ụlọ",
    wallet: "Akpa ego",
    bills: "Ụgwọ",
    airtime: "Airtime na data",
    signIn: "Banye",
    savePreferences: "Chekwaa ntọala",
    walletTitle: "Debe ego gi nso.",
    billsTitle: "Debe ihe di mkpa na-aga.",
    airtimeTitle: "Nọgide na njikọ.",
    bettingTitle: "Tinye ego na akpa egwuregwu gi.",
    giftTitle: "Zụta ma obu ree kaadi onyinye.",
    profileTitle: "Onye gi na Ravecard.",
    settingsTitle: "Mee Ravecard nke gi.",
    availableBalance: "Ego di",
    quickAccess: "Nnweta ngwa ngwa",
    recentTransactions: "Azumahia nso nso",
    personalWallet: "Akpa ego nke onwe",
    goodToSeeYou: "Obi dị m ụtọ ịhụ gị",
    homeTitle: "Ego gi na-aga n'ihu.",
    homeDescription: "Coordinator ego gi n'ohuru. Ihe niile ị chọrọ, n'otu pịa.",
    viewWallet: "Lee akpa ego",
    pulseNote: "Ihe Ravecard kwuru",
    smallMoves: "Kaadi gi. Iwu gi. Nne gi.",
    checkActivity: "Lelee azụmahịa nso nso",
    moreServices: "Ọzọ ụzọ ije ego n'ohuru — ga-apụta na Ravecard.",
    exploreMore: "Chọgharịa ọzọ",
    twoFactor: "Nyocha uzo abuo",
    authenticator: "Ngwa nyochaa",
    smsCode: "Koodu SMS",
    emailCode: "Koodu ozi-e",
    backupCodes: "Koodu ndabere",
    recommended: "Akwadoro",
    verify: "Nyochaa",
    sendCode: "Ziga koodu",
    checking: "Na-enyocha...",
    setupAuthenticator: "Tọọ ngwa nyochaa gi",
    twoFactorEnabled: "2FA na-arụ ọrụ",
    disableTwoFactor: "Gbanyụọ nyocha uzo abuo?",
  },
  es: {
    settings: "Configuracion",
    profile: "Perfil",
    home: "Inicio",
    wallet: "Billetera",
    bills: "Facturas",
    airtime: "Recargas y datos",
    signIn: "Iniciar sesion",
    savePreferences: "Guardar preferencias",
    walletTitle: "Mantén tu dinero cerca.",
    billsTitle: "Mantén lo esencial funcionando.",
    airtimeTitle: "Mantente conectado.",
    bettingTitle: "Financia tu billetera de juego.",
    giftTitle: "Compra o vende una tarjeta regalo.",
    profileTitle: "Tu identidad Ravecard.",
    settingsTitle: "Haz Ravecard tuyo.",
    availableBalance: "Saldo disponible",
    quickAccess: "Acceso rapido",
    recentTransactions: "Transacciones recientes",
    personalWallet: "Billetera personal",
    goodToSeeYou: "Qué bueno verte",
    homeTitle: "Tu dinero, en movimiento.",
    homeDescription: "Mu tu dinero libremente. Todo lo que necesitas, en un toque.",
    viewWallet: "Ver billetera",
    pulseNote: "Nota de Ravecard",
    smallMoves: "Tu tarjeta. Tus reglas. Tu libertad.",
    checkActivity: "Ver actividad reciente",
    moreServices: "Mas formas de moverte libremente — pronto en Ravecard.",
    exploreMore: "Explorar más",
    twoFactor: "Autenticacion de dos factores",
    authenticator: "Aplicacion autenticadora",
    smsCode: "Codigo SMS",
    emailCode: "Codigo por correo",
    backupCodes: "Codigos de respaldo",
    recommended: "Recomendado",
    verify: "Verificar",
    sendCode: "Enviar codigo",
    checking: "Comprobando...",
    setupAuthenticator: "Configura tu autenticador",
    twoFactorEnabled: "2FA activada",
    disableTwoFactor: "¿Desactivar la autenticacion de dos factores?",
  },
  ar: {
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    home: "الرئيسية",
    wallet: "المحفظة",
    bills: "الفواتير",
    airtime: "الرصيد والبيانات",
    signIn: "تسجيل الدخول",
    savePreferences: "حفظ التفضيلات",
    walletTitle: "احتفظ بأموالك قريبة.",
    billsTitle: "حافظ على استمرار الأساسيات.",
    airtimeTitle: "ابق على اتصال.",
    bettingTitle: "موّل محفظة اللعب.",
    giftTitle: "اشتر أو بع بطاقة هدايا.",
    profileTitle: "هويتك في Ravecard.",
    settingsTitle: "اجعل Ravecard ملكك.",
    availableBalance: "الرصيد المتاح",
    quickAccess: "وصول سريع",
    recentTransactions: "المعاملات الأخيرة",
    personalWallet: "المحفظة الشخصية",
    goodToSeeYou: "سعيد برؤيتك",
    homeTitle: "أموالك تتحرك.",
    homeDescription: " حرّك أموالك بحرية. كل ما تحتاجه، في لمسة واحدة.",
    viewWallet: "عرض المحفظة",
    pulseNote: "ملاحظة Ravecard",
    smallMoves: "بطاقتك. قواعدك. حريتك.",
    checkActivity: "عرض النشاط الأخير",
    moreServices: "المزيد من الطرق للتحرك بحرية — قريباً في Ravecard.",
    exploreMore: "استكشف المزيد",
    twoFactor: "المصادقة الثنائية",
    authenticator: "تطبيق المصادقة",
    smsCode: "رمز SMS",
    emailCode: "رمز البريد الإلكتروني",
    backupCodes: "الرموز الاحتياطية",
    recommended: "موصى به",
    verify: "تحقق",
    sendCode: "إرسال الرمز",
    checking: "جار التحقق...",
    setupAuthenticator: "إعداد تطبيق المصادقة",
    twoFactorEnabled: "المصادقة الثنائية مفعلة",
    disableTwoFactor: "تعطيل المصادقة الثنائية؟",
  },
  pt: {
    settings: "Definicoes",
    profile: "Perfil",
    home: "Inicio",
    wallet: "Carteira",
    bills: "Contas",
    airtime: "Recargas e dados",
    signIn: "Entrar",
    savePreferences: "Guardar preferencias",
    walletTitle: "Mantenha seu dinheiro perto.",
    billsTitle: "Mantenha o essencial funcionando.",
    airtimeTitle: "Fique conectado.",
    bettingTitle: "Financie sua carteira de jogo.",
    giftTitle: "Compre ou venda um cartao-presente.",
    profileTitle: "Sua identidade Ravecard.",
    settingsTitle: "Faca do Ravecard o seu espaco.",
    availableBalance: "Saldo disponivel",
    quickAccess: "Acesso rapido",
    recentTransactions: "Transacoes recentes",
    personalWallet: "Carteira pessoal",
    goodToSeeYou: "Bom ver voce",
    homeTitle: "Seu dinheiro em movimento.",
    homeDescription: "Mova seu dinheiro livremente. Tudo que voce precisa, em um toque.",
    viewWallet: "Ver carteira",
    pulseNote: "Nota Ravecard",
    smallMoves: "Seu cartao. Suas regras. Sua liberdade.",
    checkActivity: "Ver atividade recente",
    moreServices: "Mais formas de se mover livremente — em breve no Ravecard.",
    exploreMore: "Explorar mais",
    twoFactor: "Autenticacao de dois fatores",
    authenticator: "Aplicativo autenticador",
    smsCode: "Codigo SMS",
    emailCode: "Codigo por e-mail",
    backupCodes: "Codigos de recuperacao",
    recommended: "Recomendado",
    verify: "Verificar",
    sendCode: "Enviar codigo",
    checking: "Verificando...",
    setupAuthenticator: "Configure seu autenticador",
    twoFactorEnabled: "2FA ativada",
    disableTwoFactor: "Desativar a autenticacao de dois fatores?",
  },
};

type PreferencesContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const language = useSyncExternalStore<Language>(
    (onStoreChange) => {
      window.addEventListener("ravecard-language-change", onStoreChange);
      return () =>
        window.removeEventListener("ravecard-language-change", onStoreChange);
    },
    () => {
      const savedLanguage = window.localStorage.getItem("ravecard-language");
      return languageOptions.some((option) => option.value === savedLanguage)
        ? (savedLanguage as Language)
        : "en";
    },
    () => "en",
  );

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((nextLanguage: Language) => {
    window.localStorage.setItem("ravecard-language", nextLanguage);
    window.dispatchEvent(new Event("ravecard-language-change"));
  }, []);

  const value = useMemo(
    () => ({ language, setLanguage }),
    [language, setLanguage],
  );

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  );
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error("usePreferences must be used inside PreferencesProvider");
  }
  return context;
}
