"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useSyncExternalStore,
  type ReactNode,
} from "react";

export type Language = "en" | "fr" | "yo" | "ha" | "ig" | "es" | "ar" | "pt";

export const languageOptions = [
  { label: "English", value: "en" },
  { label: "French", value: "fr" },
  { label: "Yoruba", value: "yo" },
  { label: "Hausa", value: "ha" },
  { label: "Igbo", value: "ig" },
  { label: "Spanish", value: "es" },
  { label: "Arabic", value: "ar" },
  { label: "Portuguese", value: "pt" },
] as const;

export const translations: Record<Language, Record<string, string>> = {
  en: {
    settings: "Settings",
    profile: "Profile",
    home: "Home",
    wallet: "Wallet",
    bills: "Bills",
    airtime: "Airtime & Data",
    signIn: "Sign In",
    savePreferences: "Save preferences",
    walletTitle: "Keep your money close.",
    billsTitle: "Keep the essentials running.",
    airtimeTitle: "Stay connected.",
    bettingTitle: "Fund your play wallet.",
    giftTitle: "Buy or sell a gift card.",
    profileTitle: "Your Nexus identity.",
    settingsTitle: "Make Nexus yours.",
    availableBalance: "Available balance",
    quickAccess: "Quick access",
    recentTransactions: "Recent transactions",
    personalWallet: "Personal wallet",
    goodToSeeYou: "Good to see you",
    homeTitle: "Your money, in motion.",
    homeDescription: "One calm place for the payments you make every day.",
    viewWallet: "View wallet",
    nexusNote: "Nexus note",
    smallMoves: "Small moves add up.",
    checkActivity: "Check recent activity",
    moreServices: "More everyday services will appear here as Nexus grows.",
    exploreMore: "Explore more",
    twoFactor: "Two-factor authentication",
    authenticator: "Authenticator app",
    smsCode: "SMS code",
    emailCode: "Email code",
    backupCodes: "Backup codes",
    recommended: "Recommended",
    verify: "Verify",
    sendCode: "Send code",
    checking: "Checking...",
    setupAuthenticator: "Set up your authenticator",
    twoFactorEnabled: "2FA enabled",
    disableTwoFactor: "Disable two-factor authentication?",
  },
  fr: {
    settings: "Parametres",
    profile: "Profil",
    home: "Accueil",
    wallet: "Portefeuille",
    bills: "Factures",
    airtime: "Recharge & donnees",
    signIn: "Se connecter",
    savePreferences: "Enregistrer",
    walletTitle: "Gardez votre argent pres de vous.",
    billsTitle: "Gardez l'essentiel en marche.",
    airtimeTitle: "Restez connecte.",
    bettingTitle: "Alimentez votre portefeuille de jeu.",
    giftTitle: "Achetez ou vendez une carte cadeau.",
    profileTitle: "Votre identite Nexus.",
    settingsTitle: "Faites de Nexus votre espace.",
    availableBalance: "Solde disponible",
    quickAccess: "Acces rapide",
    recentTransactions: "Transactions recentes",
    personalWallet: "Portefeuille personnel",
    goodToSeeYou: "Heureux de vous revoir",
    homeTitle: "Votre argent en mouvement.",
    homeDescription: "Un espace calme pour vos paiements quotidiens.",
    viewWallet: "Voir le portefeuille",
    nexusNote: "Note Nexus",
    smallMoves: "Les petits gestes comptent.",
    checkActivity: "Voir l'activite recente",
    moreServices: "D'autres services apparaitront a mesure que Nexus grandit.",
    exploreMore: "Explorer davantage",
    twoFactor: "Authentification a deux facteurs",
    authenticator: "Application d'authentification",
    smsCode: "Code SMS",
    emailCode: "Code e-mail",
    backupCodes: "Codes de secours",
    recommended: "Recommande",
    verify: "Verifier",
    sendCode: "Envoyer le code",
    checking: "Verification...",
    setupAuthenticator: "Configurer votre authentificateur",
    twoFactorEnabled: "2FA activee",
    disableTwoFactor: "Desactiver l'authentification a deux facteurs ?",
  },
  yo: {
    settings: "Awon eto",
    profile: "Profaili",
    home: "Ile",
    wallet: "Apamowo",
    bills: "Owo isanwo",
    airtime: "Airtime ati data",
    signIn: "Wole",
    savePreferences: "Fi awon eto pam",
    walletTitle: "Pa owo re mo ara re.",
    billsTitle: "Jeki awon pataki ma n ṣiṣẹ.",
    airtimeTitle: "Wa ni asopọ.",
    bettingTitle: "Fi owo kun apamowo ere re.",
    giftTitle: "Ra tabi ta kaadi ebun.",
    profileTitle: "Idanimọ Nexus rẹ.",
    settingsTitle: "Jeki Nexus je tire.",
    availableBalance: "Iwontunwonsi to wa",
    quickAccess: "Wiwọle kiakia",
    recentTransactions: "Awon iṣowo to ṣẹṣẹ",
    personalWallet: "Apamowo ti ara ẹni",
    goodToSeeYou: "Inu mi dun lati ri e",
    homeTitle: "Owo re wa ni gbigbe.",
    homeDescription: "Ibi idakẹjẹ kan fun awon sisanwo ojoojumọ re.",
    viewWallet: "Wo apamowo",
    nexusNote: "Akọsilẹ Nexus",
    smallMoves: "Awon igbese kekere n kojọpọ.",
    checkActivity: "Wo iṣẹ to ṣẹṣẹ",
    moreServices: "Awon iṣẹ ojoojumọ diẹ sii yoo han bi Nexus ṣe n dagba.",
    exploreMore: "Ṣawari diẹ sii",
    twoFactor: "Ijẹrisi ọna meji",
    authenticator: "App ijẹrisi",
    smsCode: "Koodu SMS",
    emailCode: "Koodu imeeli",
    backupCodes: "Awon koodu afẹyinti",
    recommended: "A ṣe iṣeduro",
    verify: "Jẹrisi",
    sendCode: "Firanṣẹ koodu",
    checking: "N ṣayẹwo...",
    setupAuthenticator: "Ṣeto app ijẹrisi rẹ",
    twoFactorEnabled: "2FA ti ṣiṣẹ",
    disableTwoFactor: "Pa ijẹrisi ọna meji?",
  },
  ha: {
    settings: "Saituna",
    profile: "Bayani",
    home: "Gida",
    wallet: "Jaka",
    bills: "Kudade",
    airtime: "Airtime da data",
    signIn: "Shiga",
    savePreferences: "Ajiye saituna",
    walletTitle: "Rike kudinka kusa.",
    billsTitle: "Kula da muhimman abubuwa.",
    airtimeTitle: "Kasance a hade.",
    bettingTitle: "Cika jakar wasanka.",
    giftTitle: "Saya ko sayar da katin kyauta.",
    profileTitle: "Bayanan Nexus dinka.",
    settingsTitle: "Mayar da Nexus naka.",
    availableBalance: "Ragowar kudi",
    quickAccess: "Samun sauri",
    recentTransactions: "Ma'amaloli na baya-bayan nan",
    personalWallet: "Jakar mutum",
    goodToSeeYou: "Na yi farin cikin ganinka",
    homeTitle: "Kudinka yana tafiya.",
    homeDescription: "Wuri mai natsuwa don biyan bukatun yau da kullum.",
    viewWallet: "Duba jaka",
    nexusNote: "Bayanan Nexus",
    smallMoves: "Ƙananan matakai suna taruwa.",
    checkActivity: "Duba ayyukan baya",
    moreServices: "Ƙarin ayyuka za su bayyana yayin da Nexus ke girma.",
    exploreMore: "Bincika fiye",
    twoFactor: "Tabbatarwa mataki biyu",
    authenticator: "Manhajar tabbatarwa",
    smsCode: "Lambar SMS",
    emailCode: "Lambar imel",
    backupCodes: "Lambobin ajiya",
    recommended: "An ba da shawara",
    verify: "Tabbatar",
    sendCode: "Aika lamba",
    checking: "Ana dubawa...",
    setupAuthenticator: "Saita manhajar tabbatarwa",
    twoFactorEnabled: "2FA yana aiki",
    disableTwoFactor: "A kashe tabbatarwa mataki biyu?",
  },
  ig: {
    settings: "Ntọala",
    profile: "Profaịlụ",
    home: "Ụlọ",
    wallet: "Akpa ego",
    bills: "Ụgwọ",
    airtime: "Airtime na data",
    signIn: "Banye",
    savePreferences: "Chekwaa ntọala",
    walletTitle: "Debe ego gi nso.",
    billsTitle: "Debe ihe di mkpa na-aga.",
    airtimeTitle: "Nọgide na njikọ.",
    bettingTitle: "Tinye ego na akpa egwuregwu gi.",
    giftTitle: "Zụta ma obu ree kaadi onyinye.",
    profileTitle: "Onye gi na Nexus.",
    settingsTitle: "Mee Nexus nke gi.",
    availableBalance: "Ego di",
    quickAccess: "Nnweta ngwa ngwa",
    recentTransactions: "Azumahia nso nso",
    personalWallet: "Akpa ego nke onwe",
    goodToSeeYou: "Obi dị m ụtọ ịhụ gị",
    homeTitle: "Ego gi na-aga n'ihu.",
    homeDescription: "Otu ebe dị jụụ maka ịkwụ ụgwọ kwa ụbọchị.",
    viewWallet: "Lee akpa ego",
    nexusNote: "Ihe Nexus kwuru",
    smallMoves: "Obere mmegharị na-agbakọta.",
    checkActivity: "Lelee azụmahịa nso nso",
    moreServices: "Ọrụ kwa ụbọchị ndị ọzọ ga-apụta ka Nexus na-etolite.",
    exploreMore: "Chọgharịa ọzọ",
    twoFactor: "Nyocha uzo abuo",
    authenticator: "Ngwa nyochaa",
    smsCode: "Koodu SMS",
    emailCode: "Koodu ozi-e",
    backupCodes: "Koodu ndabere",
    recommended: "Akwadoro",
    verify: "Nyochaa",
    sendCode: "Ziga koodu",
    checking: "Na-enyocha...",
    setupAuthenticator: "Tọọ ngwa nyochaa gi",
    twoFactorEnabled: "2FA na-arụ ọrụ",
    disableTwoFactor: "Gbanyụọ nyocha uzo abuo?",
  },
  es: {
    settings: "Configuracion",
    profile: "Perfil",
    home: "Inicio",
    wallet: "Billetera",
    bills: "Facturas",
    airtime: "Recargas y datos",
    signIn: "Iniciar sesion",
    savePreferences: "Guardar preferencias",
    walletTitle: "Mantén tu dinero cerca.",
    billsTitle: "Mantén lo esencial funcionando.",
    airtimeTitle: "Mantente conectado.",
    bettingTitle: "Financia tu billetera de juego.",
    giftTitle: "Compra o vende una tarjeta regalo.",
    profileTitle: "Tu identidad Nexus.",
    settingsTitle: "Haz Nexus tuyo.",
    availableBalance: "Saldo disponible",
    quickAccess: "Acceso rapido",
    recentTransactions: "Transacciones recientes",
    personalWallet: "Billetera personal",
    goodToSeeYou: "Qué bueno verte",
    homeTitle: "Tu dinero, en movimiento.",
    homeDescription: "Un lugar tranquilo para tus pagos diarios.",
    viewWallet: "Ver billetera",
    nexusNote: "Nota de Nexus",
    smallMoves: "Los pequeños pasos suman.",
    checkActivity: "Ver actividad reciente",
    moreServices: "Aparecerán más servicios diarios a medida que Nexus crezca.",
    exploreMore: "Explorar más",
    twoFactor: "Autenticacion de dos factores",
    authenticator: "Aplicacion autenticadora",
    smsCode: "Codigo SMS",
    emailCode: "Codigo por correo",
    backupCodes: "Codigos de respaldo",
    recommended: "Recomendado",
    verify: "Verificar",
    sendCode: "Enviar codigo",
    checking: "Comprobando...",
    setupAuthenticator: "Configura tu autenticador",
    twoFactorEnabled: "2FA activada",
    disableTwoFactor: "¿Desactivar la autenticacion de dos factores?",
  },
  ar: {
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    home: "الرئيسية",
    wallet: "المحفظة",
    bills: "الفواتير",
    airtime: "الرصيد والبيانات",
    signIn: "تسجيل الدخول",
    savePreferences: "حفظ التفضيلات",
    walletTitle: "احتفظ بأموالك قريبة.",
    billsTitle: "حافظ على استمرار الأساسيات.",
    airtimeTitle: "ابق على اتصال.",
    bettingTitle: "موّل محفظة اللعب.",
    giftTitle: "اشتر أو بع بطاقة هدايا.",
    profileTitle: "هويتك في Nexus.",
    settingsTitle: "اجعل Nexus ملكك.",
    availableBalance: "الرصيد المتاح",
    quickAccess: "وصول سريع",
    recentTransactions: "المعاملات الأخيرة",
    personalWallet: "المحفظة الشخصية",
    goodToSeeYou: "سعيد برؤيتك",
    homeTitle: "أموالك تتحرك.",
    homeDescription: "مكان هادئ لمدفوعاتك اليومية.",
    viewWallet: "عرض المحفظة",
    nexusNote: "ملاحظة Nexus",
    smallMoves: "الخطوات الصغيرة تتراكم.",
    checkActivity: "عرض النشاط الأخير",
    moreServices: "ستظهر المزيد من الخدمات اليومية مع نمو Nexus.",
    exploreMore: "استكشف المزيد",
    twoFactor: "المصادقة الثنائية",
    authenticator: "تطبيق المصادقة",
    smsCode: "رمز SMS",
    emailCode: "رمز البريد الإلكتروني",
    backupCodes: "الرموز الاحتياطية",
    recommended: "موصى به",
    verify: "تحقق",
    sendCode: "إرسال الرمز",
    checking: "جار التحقق...",
    setupAuthenticator: "إعداد تطبيق المصادقة",
    twoFactorEnabled: "المصادقة الثنائية مفعلة",
    disableTwoFactor: "تعطيل المصادقة الثنائية؟",
  },
  pt: {
    settings: "Definicoes",
    profile: "Perfil",
    home: "Inicio",
    wallet: "Carteira",
    bills: "Contas",
    airtime: "Recargas e dados",
    signIn: "Entrar",
    savePreferences: "Guardar preferencias",
    walletTitle: "Mantenha seu dinheiro perto.",
    billsTitle: "Mantenha o essencial funcionando.",
    airtimeTitle: "Fique conectado.",
    bettingTitle: "Financie sua carteira de jogo.",
    giftTitle: "Compre ou venda um cartao-presente.",
    profileTitle: "Sua identidade Nexus.",
    settingsTitle: "Faca do Nexus o seu espaco.",
    availableBalance: "Saldo disponivel",
    quickAccess: "Acesso rapido",
    recentTransactions: "Transacoes recentes",
    personalWallet: "Carteira pessoal",
    goodToSeeYou: "Bom ver voce",
    homeTitle: "Seu dinheiro em movimento.",
    homeDescription: "Um lugar tranquilo para os pagamentos do dia a dia.",
    viewWallet: "Ver carteira",
    nexusNote: "Nota Nexus",
    smallMoves: "Pequenos passos fazem a diferenca.",
    checkActivity: "Ver atividade recente",
    moreServices: "Mais servicos diarios aparecerao conforme a Nexus crescer.",
    exploreMore: "Explorar mais",
    twoFactor: "Autenticacao de dois fatores",
    authenticator: "Aplicativo autenticador",
    smsCode: "Codigo SMS",
    emailCode: "Codigo por e-mail",
    backupCodes: "Codigos de recuperacao",
    recommended: "Recomendado",
    verify: "Verificar",
    sendCode: "Enviar codigo",
    checking: "Verificando...",
    setupAuthenticator: "Configure seu autenticador",
    twoFactorEnabled: "2FA ativada",
    disableTwoFactor: "Desativar a autenticacao de dois fatores?",
  },
};

type PreferencesContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const language = useSyncExternalStore<Language>(
    (onStoreChange) => {
      window.addEventListener("nexus-language-change", onStoreChange);
      return () =>
        window.removeEventListener("nexus-language-change", onStoreChange);
    },
    () => {
      const savedLanguage = window.localStorage.getItem("nexus-language");
      return languageOptions.some((option) => option.value === savedLanguage)
        ? (savedLanguage as Language)
        : "en";
    },
    () => "en",
  );

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((nextLanguage: Language) => {
    window.localStorage.setItem("nexus-language", nextLanguage);
    window.dispatchEvent(new Event("nexus-language-change"));
  }, []);

  const value = useMemo(
    () => ({ language, setLanguage }),
    [language, setLanguage],
  );

  return (
    <PreferencesContext.Provider value={value}>
      {children}
    </PreferencesContext.Provider>
  );
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error("usePreferences must be used inside PreferencesProvider");
  }
  return context;
}
